'use client';
import { configuredUrl } from '../../../lib/configured-url';
import { FormEvent, useEffect, useState } from 'react';
const apiUrl = configuredUrl(process.env.NEXT_PUBLIC_QUEUEFLOW_API_URL, '', true);
const adminUrl = configuredUrl(process.env.NEXT_PUBLIC_QUEUEFLOW_ADMIN_URL, '', true);
type Invitation = { maskedEmail: string; organizationName: string | null; status: string; canRequestVerificationCode: boolean; isVerified: boolean };
export function ActivationFlow({ token }: { token: string }) {
  const [activationAuthorization, setActivationAuthorization] = useState('');
  const [email, setEmail] = useState(''); const [invitation, setInvitation] = useState<Invitation>(); const [stage, setStage] = useState<'loading'|'verify'|'complete'|'done'|'error'>('loading'); const [message, setMessage] = useState(''); const [devCode, setDevCode] = useState('');
  useEffect(() => { fetch(`${apiUrl}/api/v1/public/activation/lookup`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ invitationToken: token }), cache: 'no-store' }).then(async response => { if (!response.ok) throw new Error(); const data = await response.json() as Invitation; if (!['Pending', 'Verified'].includes(data.status)) throw new Error(); setInvitation(data); setStage('verify'); }).catch(() => { setMessage('Este convite não está disponível.'); setStage('error'); }); }, [token]);
  async function requestCode() { const response = await fetch(`${apiUrl}/api/v1/public/activation/request-code`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ invitationToken: token }) }); const data = await response.json().catch(() => ({})) as { developmentCode?: string; detail?: string }; if (!response.ok) { setMessage(data.detail ?? 'Não foi possível enviar o código.'); return; } setDevCode(data.developmentCode ?? ''); setMessage('Enviamos um código para o e-mail do convite.'); }
  async function verify(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const code = new FormData(event.currentTarget).get('code'); const response = await fetch(`${apiUrl}/api/v1/public/activation/verify`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ invitationToken: token, code }) }); if (!response.ok) { setMessage('Código inválido ou expirado.'); return; } const grant = await response.json() as { activationAuthorization: string }; setActivationAuthorization(grant.activationAuthorization); setStage('complete'); setMessage('E-mail confirmado.'); }
  async function complete(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const response = await fetch(`${apiUrl}/api/v1/public/activation/complete`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ invitationToken: token, activation: { activationAuthorization, organizationName: values.get('organizationName'), slug: values.get('slug') || null, responsibleName: values.get('responsibleName'), password: values.get('password'), timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'America/Sao_Paulo' } }) }); const data = await response.json().catch(() => ({})) as { detail?: string; email?: string }; if (!response.ok) { if (response.status === 404) { setActivationAuthorization(''); setStage('verify'); } setMessage(data.detail ?? 'Não foi possível concluir a ativação.'); return; } setActivationAuthorization(''); setEmail(data.email ?? ''); setStage('done'); }
  if (stage === 'loading') return <p>Carregando convite…</p>; if (stage === 'error') return <><h1>Convite indisponível</h1><p className="join-error">{message}</p></>; if (stage === 'done') return <><h1>Conta ativada</h1><p>Sua organização foi criada. Agora entre no painel administrativo com o e-mail convidado.</p>{adminUrl ? <a className="service-action" href={`${adminUrl}/login?email=${encodeURIComponent(email)}&activated=1`}>Ir para o Admin</a> : <p>Endereço do Admin não configurado.</p>}</>;
  return <><h1>Ative sua organização</h1><p>Convite para <strong>{invitation?.organizationName ?? 'sua empresa'}</strong>.</p><p className="muted">Confirmaremos o e-mail {invitation?.maskedEmail} antes da criação.</p>{stage === 'verify' ? <><button type="button" onClick={requestCode} disabled={!invitation?.canRequestVerificationCode}>Enviar código</button>{devCode && <p className="muted">Código de desenvolvimento: {devCode}</p>}<form className="booking-form" onSubmit={verify}><label>Código de 6 dígitos<input name="code" inputMode="numeric" pattern="[0-9]{6}" required /></label><button>Confirmar e-mail</button></form></> : <form className="booking-form" onSubmit={complete}><label>Nome da empresa<input name="organizationName" defaultValue={invitation?.organizationName ?? ''} required /></label><label>Slug público (opcional)<input name="slug" /></label><label>Seu nome<input name="responsibleName" required /></label><label>Crie uma senha<input name="password" type="password" minLength={12} required /></label><button>Ativar e entrar na configuração</button></form>}{message && <p className={message.includes('inválido') ? 'join-error' : 'muted'}>{message}</p>}</>;
}
