'use client';
import { HubConnectionBuilder } from '@microsoft/signalr';
import { useEffect, useState } from 'react';
type Call = { ticketNumber: string; counterName: string; calledAt?: string };
export function BranchDisplayScreen({ queuePublicIds, organizationName, branchName, initialCalls }: { queuePublicIds: string[]; organizationName: string; branchName: string; initialCalls: Call[] }) {
  const [current, setCurrent] = useState<Call | undefined>(initialCalls[0]); const [history, setHistory] = useState<Call[]>(initialCalls.slice(0, 10)); const [connected, setConnected] = useState(false);
  useEffect(() => { const connection = new HubConnectionBuilder().withUrl(`${process.env.NEXT_PUBLIC_QUEUEFLOW_API_URL ?? 'http://localhost:5260'}/hubs/queue`).withAutomaticReconnect().build(); const receive = (call: Call) => { setCurrent(call); setHistory(items => [call, ...items.filter(item => item.ticketNumber !== call.ticketNumber)].slice(0, 10)); }; connection.on('ticket.called', receive); connection.on('ticket.recalled', receive); connection.onreconnecting(() => setConnected(false)); connection.onreconnected(async () => { await Promise.all(queuePublicIds.map(id => connection.invoke('JoinQueueGroup', id))); setConnected(true); }); connection.start().then(() => Promise.all(queuePublicIds.map(id => connection.invoke('JoinQueueGroup', id)))).then(() => setConnected(true)).catch(() => setConnected(false)); return () => { void connection.stop(); }; }, [queuePublicIds]);
  return <main><header className="display-header"><b>{organizationName}</b><span>{branchName} <i className="connection">{connected ? '● conectado' : '○ reconectando'}</i></span></header><section className="display-grid"><article className="current-call">{current ? <><small>SENHA CHAMADA</small><h1>{current.ticketNumber}</h1><h2>GUICHÊ {current.counterName}</h2></> : <div className="waiting-call"><h2>Aguardando próxima chamada</h2></div>}</article><aside className="call-history"><h3>ÚLTIMAS CHAMADAS</h3>{history.length ? history.map((call, index) => <p key={`${call.ticketNumber}-${index}`}><span>{call.ticketNumber}</span><b>{call.counterName}</b></p>) : <p>Nenhuma chamada ainda</p>}</aside></section></main>;
}
