import Link from 'next/link'; import { redirect } from 'next/navigation';
import { AdminShell } from '../../components/admin-shell'; import { authFailure } from '../../lib/auth'; import { getBranches } from '../../lib/server-branches'; import { getServerSession } from '../../lib/server-session'; import { getUsers } from '../../lib/server-users'; import { canManageUser, roleLabels } from '../../lib/users'; import { UserCreateForm } from './user-create-form'; import { UserStatusButton } from './user-status-button';
export default async function UsersPage() {
  const session = await getServerSession(); if (authFailure(session.status) === 'unauthorized') redirect('/api/auth/refresh?returnTo=/users'); if (!session.user || !['Owner', 'Admin', 'Manager'].includes(session.user.role)) return <Denied />;
  const [users, branches] = await Promise.all([getUsers(), getBranches()]); if (users.status === 401 || branches.status === 401) redirect('/api/auth/refresh?returnTo=/users'); if (!users.data || !branches.data) throw new Error('Não foi possível carregar os usuários.');
  return <AdminShell user={session.user}><div className="section-heading"><div><h3>Usuários e permissões</h3><p className="muted">Controle quem administra e quem opera cada unidade.</p></div></div><UserCreateForm actorRole={session.user.role} branches={branches.data} />
    <div className="table-wrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Unidades</th><th>Status</th><th></th></tr></thead><tbody>{users.data.map(user => <tr key={user.id}><td>{user.name}</td><td>{user.email}</td><td>{roleLabels[user.role]}</td><td>{user.branchIds.map(id => branches.data!.find(x => x.id === id)?.name).filter(Boolean).join(', ') || 'Todas / não aplicável'}</td><td><span className={`status ${user.isActive ? 'active' : 'inactive'}`}>{user.isActive ? 'Ativo' : 'Inativo'}</span></td><td>{canManageUser(session.user!.role, user.role) && <div className="form-actions"><Link href={`/users/${user.id}`}>Editar</Link><UserStatusButton id={user.id} active={user.isActive} /></div>}</td></tr>)}</tbody></table></div>
  </AdminShell>;
}
function Denied() { return <main className="centered"><section className="notice"><h1>Acesso não permitido</h1><p>Seu perfil não pode administrar usuários.</p></section></main>; }
