'use client';
import { FormEvent, useState } from 'react';
import type { PlatformInvitation } from '../../../../lib/server-platform';
type Issued = { invitation: PlatformInvitation; activationUrl: string; canSendInvitation: boolean };
export function InvitationManager({ initial }: { initial: PlatformInvitation[] }) {
  const [issued, setIssued] = useState<Issued>(); const [items, setItems] = useState(initial); const [message, setMessage] = useState(''); const [created, setCreated] = useState('');
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); const response = await fetch('/api/platform/invitations', { method: 'POST', headers: { 'Content-Type':'application/json' }, body: JSON.stringify({ email: form.get('email'), responsibleName: form.get('responsibleName'), organizationName: form.get('organizationName'), plan: form.get('plan') }) }); const body = await response.json() as Issued & { message?: string }; if (!response.ok) { setMessage(body.message ?? 'Não foi possível criar o convite.'); return; } setItems([body.invitation, ...items]); setCreated(body.activationUrl); setIssued(body); setMessage('Convite criado. Copie o link agora; ele não será exibido novamente.'); element.reset(); }
  async function action(id: string, action: 'revoke'|'reissue') { const response = await fetch(`/api/platform/invitations/${id}/${action}`, { method: 'POST' }); if (!response.ok) { setMessage('Não foi possível concluir a ação.'); return; } if (action === 'revoke') { setItems(items.map(item => item.id === id ? { ...item, status: 'Revoked' as const, revokedAt: new Date().toISOString() } : item)); setMessage('Convite revogado.'); return; } const body = await response.json() as Issued; setItems([body.invitation, ...items.map(item => item.id === id ? { ...item, status: 'Revoked' as const, revokedAt: new Date().toISOString() } : item)]); setCreated(body.activationUrl); setIssued(body); setMessage('Novo convite emitido. Copie o novo link agora.'); }
  async function send() { if (!issued) return; const token = new URL(issued.activationUrl).hash.slice(1); const response = await fetch(`/api/platform/invitations/${issued.invitation.id}/send`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token }) }); setMessage(response.ok ? 'Convite enviado.' : 'Não foi possível enviar o convite.'); }
  async function copy() { await navigator.clipboard.writeText(created); setMessage('Link copiado.'); }
  return <div className="stack"><form className="card form-grid" onSubmit={create}><h2>Novo convite</h2><label>E-mail do owner<input name="email" type="email" required /></label><label>Responsável<input name="responsibleName" /></label><label>Empresa<input name="organizationName" required /></label><label>Plano<select name="plan" defaultValue="Trial"><option>Trial</option></select></label><button>Criar convite</button></form>{created && <section className="card"><strong>Link de ativação</strong><p className="copy-url">{created}</p><button type="button" onClick={copy}>Copiar link</button>{issued?.canSendInvitation && <button type="button" onClick={send}>Enviar convite</button>}</section>}{message && <p className="form-success">{message}</p>}<section className="table-card"><table><thead><tr><th>E-mail</th><th>Empresa</th><th>Status</th><th>Expira</th><th></th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.email}</td><td>{item.organizationName ?? '—'}</td><td>{item.status}</td><td>{new Date(item.expiresAt).toLocaleString('pt-BR')}</td><td>{(item.status === 'Pending' || item.status === 'Verified') && <button className="secondary" type="button" onClick={() => action(item.id, 'revoke')}>Revogar</button>} {item.status !== 'Used' && item.status !== 'Revoked' && <button className="secondary" type="button" onClick={() => action(item.id, 'reissue')}>Reemitir</button>}</td></tr>)}</tbody></table></section></div>;
}
